- name: 安装 haproxy
  yum:
      state: present 
      name: haproxy
- name: 复制 haproxy.cfg
  template:
          src: haproxy.cfg.j2
          dest: /etc/haproxy/haproxy.cfg
- name: 运行 haproxy
  service:
         name: haproxy
         state: started 
         enabled: true
